SFTPGO: optional http ingress and optional sidecar support
sagikazarmark/helm-charts pull request #109
Opened 2021-07-16 15:52 UTC by bdashrad

This adds support for optional sidecars in the pod and an optional ingress controller for an httpd service.

2021-07-19 15:52 UTC, bdashrad commented
@sagikazarmark let me know if you need me to add anything additional to this for review. We need sidecar support to use GCP cloud-sql-proxy for the config database. (https://cloud.google.com/sql/docs/mysql/connect-kubernetes-engine)

2021-07-20 17:37 UTC, sagikazarmark commented
@bdashrad thanks for the contribution!

Why do you need to run the proxy as a sidecar?

I used [this](https://artifacthub.io/packages/helm/rimusz/gcloud-sqlproxy) Helm chart with success in the past.

Are there any specific reasons why it has to run as a sidecar?

2021-07-20 17:41 UTC, sagikazarmark commented
A quick google search also pointed me to [this](https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/230) issue and then these projects:

- https://github.com/tumblr/k8s-sidecar-injector/
- https://github.com/connctd/sqlbee

Personally I find webhook based solutions much better for this kind of issues, because it keeps Helm charts simple while giving you total control over the created resources.

So even if running the proxy as a sidecar is a requirement, I'd consider using the webhook based solution instead. Let me know if it works for you.

2021-07-21 14:15 UTC, bdashrad commented
The sidecar injection should meet our needs, but is definitely much more work than being able to add them to the pod from the values.yaml. I think this is still a worthy addition even though there are other options.

2022-12-20 10:29 UTC, sagikazarmark requested changes
@bdashrad sorry for the long delay.

I had a few comments. Happy to merge once those are addressed and the branch is rebased.

2022-12-20 10:29 UTC, sagikazarmark commented on charts/sftpgo/values.yaml
> +# -- Additional containers to add to the pod
```suggestion
# -- Additional containers to add to the pod.
```

2022-12-20 10:29 UTC, sagikazarmark commented on charts/sftpgo/README.md
> +| sidecarContainers | object | `{}` | Additional containers to run in the pod alongside the sftpgo container. |
Please run `make docs`

2022-12-20 10:29 UTC, sagikazarmark commented on charts/sftpgo/Chart.yaml
> +version: 0.9.0
Please add changelog as well

2023-02-15 16:28 UTC, bdashrad commented on charts/sftpgo/Chart.yaml
> +version: 0.9.0
Done

2023-02-15 16:29 UTC, bdashrad commented
@sagikazarmark sorry for the delay, I don't know how I missed your comments. PR updated with requested changes and merged in latest main branch.

2025-02-12 17:23 UTC, sagikazarmark commented
The chart is being migrated to https://github.com/sftpgo/helm-chart

Please submit PRs there. Thanks

2025-02-12 17:23 UTC, closed without merging