add `httpd.enabled` toggle
sagikazarmark/helm-charts pull request #124
Opened 2022-01-02 01:20 UTC by mike-k0

Closes #122 

This patch introduces a new setting, `httpd.enabled`

By default, this value is `true`. 

If it is set to `false`, the HTTP service will no longer be exposed, and the `SFTPGO_HTTPD__BINDINGS__0__PORT` environmental variable will set the port binding to `0` (which prevents SFTPGo from launching the HTTP daemon altogether).

2022-01-02 11:27 UTC, sagikazarmark requested changes
Thanks @mike-k0 !

Two things that I need you to change before merging:
- Please add the new variable to the two ingresses as well to make sure they are not created even if they are enabled (they rely on httpd)
- Please update the version in Chart.yaml then run make docs in the repo root

Thanks!

2022-01-02 19:45 UTC, trippy22 commented
> Thanks @mike-k0 !
> 
> Two things that I need you to change before merging:
> 
> * Please add the new variable to the two ingresses as well to make sure they are not created even if they are enabled (they rely on httpd)
> * Please update the version in Chart.yaml then run make docs in the repo root
> 
> Thanks!

Hi @sagikazarmark - thank you for the feedback!

The patch should now include the changes requested. Please let me know if there's anything else!

2022-01-02 20:23 UTC, mike-k0 commented
> Thanks @mike-k0 !
> 
> Two things that I need you to change before merging:
> 
> * Please add the new variable to the two ingresses as well to make sure they are not created even if they are enabled (they rely on httpd)
> * Please update the version in Chart.yaml then run make docs in the repo root
> 
> Thanks!

Hi @sagikazarmark - thank you for the feedback!

The patch should now include the changes requested. Please let me know if there's anything else!

2022-01-03 16:13 UTC, sagikazarmark approved these changes
Thanks @mike-k0

2022-01-03 16:13 UTC, merged