add value in Helm chant for log-level for kube-secrets-init
sagikazarmark/helm-charts pull request #152
Opened 2022-06-07 10:20 UTC by Kydybets

2022-06-07 10:21 UTC, Kydybets commented
@sagikazarmark  could you please review and provide your feedback?

2022-06-07 22:07 UTC, sagikazarmark requested changes
Thanks @Kydybets for the contribution. Please read the contribution guide and apply the steps there, particularly:

- generating docs
- bumping chart version
- updating change log

Thanks!

2022-06-08 06:43 UTC, Kydybets commented
Thank you @sagikazarmark  for the comments.
I am new to contributing to open-source projects.
Unfortunately didn't find guide for contributors in the repo, try to do the same way like you do before for this chart

2022-06-08 06:43 UTC, Kydybets commented on charts/kube-secrets-init/values.yaml
> +# could be "info", "debug", "warning", "error", "fatal", "panic"
commited

2022-06-21 10:24 UTC, Kydybets commented
@sagikazarmark  is there any required?

2022-07-29 14:51 UTC, Kydybets commented
@sagikazarmark  can you provide feedback please?

2022-07-29 15:00 UTC, sagikazarmark commented
Can you please squash your commits to retrigger CI?

2022-07-29 15:11 UTC, closed without merging