sftpgo: config for deployment strategy
sagikazarmark/helm-charts pull request #182
Opened 2022-12-22 11:56 UTC by bitnik

2022-12-22 12:59 UTC, sagikazarmark requested changes
Thanks for the high quality PR @bitnik!

I had one minor note, easily fixable. Can you please take a look?

Thanks!

2022-12-22 12:59 UTC, sagikazarmark commented on charts/sftpgo/templates/deployment.yaml
> +  {{- end }}
```suggestion
  {{- with .Values.deploymentStrategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
```

2022-12-22 13:08 UTC, bitnik commented
Done. Thank you for the quick review @sagikazarmark!

2022-12-23 05:08 UTC, sagikazarmark approved these changes

2022-12-23 05:08 UTC, merged